### ISSUE TITLE
Use sf2dlib for rendering instead of software

### ISSUE THREAD

**Issue by handsomematt** [MrJPGames/Mastermind-3DS#2]
sf2dlib is a simple and fast 2D library, much better than software rendering https://github.com/xerpi/sf2dlib

**Comment by MrJPGames** [comment]
Currently SR is fast enough, as changing rendering code to work with sf2dlib will take a little while it will keep using SR for the time being, if I've got some spare time though I will update the rendering code. (There is one thing that is not rendered under the condition of an end of game because SR was to slow to support it, so there is indeed a reason to stop using SR).

I btw, didn't know of this library I haven't made any 3DS homebrew since just after nh 1.0's release so yeah.
Thanks for reporting this to me (together with the outdated ctrulib!)

**Comment by MrJPGames** [comment]
Can't get sf2dlib to install. Won't fix until I might try again at some point to get the lib installed.
